name: MorphWave
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=mkl
  - absl-py=0.15.0=pyhd3eb1b0_0
  - aiohttp=3.8.1=py37h7f8727e_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astor=0.8.1=py37h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - asynctest=0.13.0=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py37h06a4308_0
  - bottleneck=1.3.4=py37hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.6.15=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - cryptography=3.4.8=py37hd23ed53_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.2.0=py37h7f8727e_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h5202010_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.42.0=py37hce63b2e_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9b=0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py37h2531618_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=py37h06a4308_0
  - matplotlib=3.5.0=py37h06a4308_0
  - matplotlib-base=3.5.0=py37h3ed280b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - multidict=5.2.0=py37h7f8727e_2
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.7.2=0
  - numexpr=2.8.1=py37h6abb31d_0
  - numpy=1.21.2=py37h20f2e39_0
  - numpy-base=1.21.2=py37h79a1101_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=py37_0
  - openssl=1.1.1q=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h8c16a72_0
  - pcre=8.45=h295c915_0
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.2.2=py37h06a4308_0
  - protobuf=3.17.2=py37h295c915_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.1.0=py37h06a4308_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_1
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - pytorch=1.7.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2022.1=py37h06a4308_0
  - pyyaml=6.0=py37h7f8727e_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.7.1=py37h292c36d_2
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=58.0.4=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tenacity=8.0.1=py37h06a4308_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.0=py37hca6d32c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.4.1=mkl_py37h2d14ff2_0
  - tensorflow-base=2.4.1=mkl_py37h43e0292_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=1.1.0=py37h06a4308_1
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.7.2=py37
  - torchvision=0.8.2=py37_cu101
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - wrapt=1.13.3=py37h7f8727e_2
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py37h27cfd23_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=0
  - zstd=1.4.9=haebb681_0
  - pip:
    - adjusttext==0.7.3
    - autopep8==1.6.0
    - beautifulsoup4==4.10.0
    - bioinfokit==2.0.8
    - easydict==1.9
    - filelock==3.4.2
    - flake8==4.0.1
    - gdown==4.2.0
    - importlib-metadata==4.2.0
    - kaleido==0.2.1
    - matplotlib-venn==0.11.7
    - mccabe==0.6.1
    - patsy==0.5.2
    - plotly==5.8.0
    - pv==0.1.3
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - scikit-learn==1.0.2
    - simplejson==3.17.6
    - sklearn==0.0
    - soupsieve==2.3.1
    - statsmodels==0.13.2
    - tabulate==0.8.10
    - textwrap3==0.9.2
    - threadpoolctl==3.1.0
    - toml==0.10.2
    - trimesh==3.10.2
    - webob==1.4.1
